# -*- coding: utf-8 -*-
"""task-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ayMFCEbqoO4-tGRdTDl6jjdI8aY-O3_A
"""

import random

def determine_winner(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "It's a tie!"
    elif (
        (user_choice == "rock" and computer_choice == "scissors") or
        (user_choice == "scissors" and computer_choice == "paper") or
        (user_choice == "paper" and computer_choice == "rock")
    ):
        return "You win!"
    else:
        return "You lose!"

def rps_game():
    user_score = 0
    computer_score = 0

    print("Rock-Paper-Scissors Game")

    while True:
        print("\nChoose: rock, paper, or scissors (type 'exit' to end)")

        user_choice = input("Your choice: ").lower()

        if user_choice == 'exit':
            print("Thanks for playing! Final scores:")
            print(f"You: {user_score}, Computer: {computer_score}")
            break

        if user_choice not in ['rock', 'paper', 'scissors']:
            print("Invalid choice. Please choose rock, paper, or scissors.")
            continue

        computer_choice = random.choice(['rock', 'paper', 'scissors'])

        print(f"\nYou chose: {user_choice}")
        print(f"Computer chose: {computer_choice}")

        result = determine_winner(user_choice, computer_choice)
        print(result)

        if "win" in result:
            user_score += 1
        elif "lose" in result:
            computer_score += 1

        print(f"\nCurrent scores - You: {user_score}, Computer: {computer_score}")

# Run the Rock-Paper-Scissors game
rps_game()